# Generated by Django 2.2.4 on 2019-10-15 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientes_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informes_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Clientes')),
            ],
        ),
    ]
