# Generated by Django 2.2.4 on 2019-10-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informes',
            name='adelanto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='informes',
            name='bancario',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='informes',
            name='efectivo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='informes',
            name='tarjeta',
            field=models.IntegerField(default=0),
        ),
    ]
