# Generated by Django 2.2.4 on 2019-10-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20191016_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informes',
            old_name='votes',
            new_name='cantidad',
        ),
    ]
