# Generated by Django 2.2.4 on 2019-10-16 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_text', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(default=0)),
                ('efectivo', models.IntegerField(default=0)),
                ('tarjeta', models.IntegerField(default=0)),
                ('bancario', models.IntegerField(default=0)),
                ('pagos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Pagos')),
            ],
        ),
    ]
