# Generated by Django 2.2.4 on 2019-10-17 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20191016_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informes_text', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(default=0)),
                ('efectivo', models.IntegerField(default=0)),
                ('tarjeta', models.IntegerField(default=0)),
                ('bancario', models.IntegerField(default=0)),
                ('adelanto', models.IntegerField(default=0)),
                ('sesenta', models.IntegerField(default=0)),
                ('treinta', models.IntegerField(default=0)),
                ('diez', models.IntegerField(default=0)),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Clientes')),
            ],
        ),
    ]
