# Generated by Django 2.2.4 on 2019-10-17 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_auto_20191016_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informes',
            old_name='adelanto',
            new_name='Factura',
        ),
        migrations.RenameField(
            model_name='informes',
            old_name='sesenta',
            new_name='Sesenta',
        ),
        migrations.RenameField(
            model_name='informes',
            old_name='tarjeta',
            new_name='Tarjeta',
        ),
        migrations.RenameField(
            model_name='informes',
            old_name='treinta',
            new_name='Treinta',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='clientes',
        ),
    ]
