# Generated by Django 2.2.4 on 2019-10-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_auto_20191016_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informes',
            name='bancario',
        ),
        migrations.RemoveField(
            model_name='informes',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='informes',
            name='diez',
        ),
        migrations.RemoveField(
            model_name='informes',
            name='efectivo',
        ),
        migrations.AddField(
            model_name='informes',
            name='Bancario',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='informes',
            name='Cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='informes',
            name='Diez',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='informes',
            name='Efectivo',
            field=models.IntegerField(default=0),
        ),
    ]
