# Generated by Django 2.2.4 on 2019-10-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_auto_20191016_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='pedido',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagos',
            name='clientes_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
