# Generated by Django 2.2.4 on 2019-10-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_auto_20191016_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='pedido',
        ),
        migrations.AddField(
            model_name='informes',
            name='Pedido',
            field=models.IntegerField(default=0),
        ),
    ]
