# Generated by Django 2.2.4 on 2019-10-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_auto_20191016_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='informes',
            name='Beneficios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='informes',
            name='Total_gastos',
            field=models.IntegerField(default=0),
        ),
    ]
