# Generated by Django 2.2.4 on 2019-10-17 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informe_text', models.CharField(max_length=200)),
                ('Numero_Pedido', models.IntegerField(default=0)),
                ('Nombre', models.IntegerField(default=0)),
                ('Domicilio', models.IntegerField(default=0)),
                ('Fecha', models.IntegerField(default=0)),
                ('Unidades', models.IntegerField(default=0)),
                ('Importe_Sesenta', models.IntegerField(default=0)),
                ('Importe_Treinta', models.IntegerField(default=0)),
                ('Importe_diez', models.IntegerField(default=0)),
                ('Nazani', models.IntegerField(default=0)),
                ('Importacion', models.IntegerField(default=0)),
                ('Mosquitero', models.IntegerField(default=0)),
                ('Vidrios', models.IntegerField(default=0)),
                ('Albanil', models.IntegerField(default=0)),
                ('Instalacion', models.IntegerField(default=0)),
                ('Extras', models.IntegerField(default=0)),
                ('Total_gastos', models.IntegerField(default=0)),
                ('Beneficios', models.IntegerField(default=0)),
                ('Pendientes', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpe.Cliente')),
            ],
        ),
    ]
