# Generated by Django 2.2.4 on 2019-10-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpe', '0002_auto_20191017_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='Emil',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='informe',
            name='Telefono',
            field=models.IntegerField(default=0),
        ),
    ]
