# Generated by Django 2.2.4 on 2019-10-19 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erpe', '0004_auto_20191018_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='Numero_Producto',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='Total_gastos',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_gastos', models.CharField(max_length=20)),
                ('total', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpe.Cliente')),
            ],
        ),
    ]
