# Generated by Django 2.2.4 on 2019-10-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpe', '0005_auto_20191018_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='Total_gastos',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
